# Generated by Django 5.2 on 2025-12-08 10:18

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('published_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=books.models.book_pdf_upload_to)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=books.models.book_cover_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
